# Generated by Django 4.0.4 on 2022-05-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='product title')),
                ('content', models.TextField(verbose_name='product content')),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=6, verbose_name='product price')),
            ],
        ),
    ]
